# Generated by Django 2.2.4 on 2019-12-05 03:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default='1', max_length=2)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('01', 'Acre (AC)'), ('02', 'Alagoas (AL)'), ('03', 'Amapá (AP)'), ('04', 'Amazonas (AM)'), ('05', 'Bahia (BA)'), ('06', 'Ceará (CE)'), ('07', 'Distrito Federal (DF)'), ('08', 'Espírito Santo (ES)'), ('09', 'Goiás (GO)'), ('10', 'Maranhão (MA)'), ('11', 'Mato Grosso (MT)'), ('12', 'Mato Grosso do Sul (MS)'), ('13', 'Minas Gerais (MG)'), ('14', 'Pará (PA)'), ('15', 'Paraíba (PB)'), ('16', 'Paraná (PR)'), ('17', 'Pernambuco (PE)'), ('18', 'Piauí (PI)'), ('19', 'Rio de Janeiro (RJ)'), ('20', 'Rio Grande do Norte (RN)'), ('21', 'Rio Grande do Sul (RS)'), ('22', 'Rondônia (RO)'), ('23', 'Roraima (RR)'), ('24', 'Santa Catarina (SC)'), ('25', 'São Paulo (SP)'), ('26', 'Sergipe (SE)'), ('27', 'Tocantins (TO)')], default='12', max_length=2)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 3, 59, 8, 309666, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='funcaoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='cadastroSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Não visualizado'), ('2', 'Visualizado')], default=1, max_length=1)),
                ('estadoCivil', models.CharField(choices=[('1', 'Solteiro(a)'), ('2', 'Casado(a)'), ('3', 'Separado(a)'), ('4', 'Divorciado(a)'), ('5', 'Viúvo(a)')], default=1, max_length=1)),
                ('experiencia', models.CharField(choices=[('1', 'Menos de 1 ano'), ('2', '1 ano'), ('3', '2 anos'), ('4', '3 anos'), ('5', 'Mais de 3 anos')], max_length=1)),
                ('escolaridade', models.CharField(choices=[('1', 'Ensino Fundamental Incompleto'), ('2', 'Ensino Fundamental Completo'), ('3', 'Ensino Médio Incompleto'), ('4', 'Ensino Médio Completo'), ('5', 'Superior Incompleto'), ('6', 'Superior Completo')], default=1, max_length=1)),
                ('ehDeTresLagoas', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, null=True)),
                ('trabalhouInomont', models.CharField(blank=True, choices=[('1', 'Sim'), ('2', 'Não')], default=1, max_length=1, null=True)),
                ('pqInomont', models.CharField(blank=True, max_length=400, null=True)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('empresa1', models.CharField(blank=True, max_length=300, null=True)),
                ('funcao1', models.CharField(blank=True, max_length=300, null=True)),
                ('periodo1', models.CharField(choices=[('1', 'De 1 a 6 meses'), ('2', 'De 6 a 12 meses'), ('3', 'De 1 ano a 1 ano e meio'), ('4', 'De 1 ano e meio a 2 anos'), ('5', 'Mais de 2 anos')], max_length=1)),
                ('empresa2', models.CharField(blank=True, max_length=300, null=True)),
                ('funcao2', models.CharField(blank=True, max_length=300, null=True)),
                ('periodo2', models.CharField(choices=[('1', 'De 1 a 6 meses'), ('2', 'De 6 a 12 meses'), ('3', 'De 1 ano a 1 ano e meio'), ('4', 'De 1 ano e meio a 2 anos'), ('5', 'Mais de 2 anos')], max_length=1)),
                ('empresa3', models.CharField(blank=True, max_length=300, null=True)),
                ('funcao3', models.CharField(blank=True, max_length=300, null=True)),
                ('periodo3', models.CharField(choices=[('1', 'De 1 a 6 meses'), ('2', 'De 6 a 12 meses'), ('3', 'De 1 ano a 1 ano e meio'), ('4', 'De 1 ano e meio a 2 anos'), ('5', 'Mais de 2 anos')], max_length=1)),
                ('dataNasc', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 3, 59, 8, 414627, tzinfo=utc))),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 3, 59, 8, 414671, tzinfo=utc))),
                ('funcao', models.ForeignKey(on_delete='models.CASCADE', to='website.funcaoModel')),
            ],
        ),
    ]
