# Generated by Django 2.2.4 on 2019-12-27 00:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradormodel',
            name='cadastroBase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.cadastroSite'),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 0, 48, 48, 444039, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 0, 48, 48, 444001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='experiencia',
            field=models.CharField(choices=[('-1', 'Menos de 1 ano'), ('2', '1 ano'), ('3', '2 anos'), ('4', '3 anos'), ('5', 'Mais de 3 anos')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 0, 48, 48, 398221, tzinfo=utc)),
        ),
    ]
