# Generated by Django 2.2.4 on 2019-12-17 00:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191216_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedormodel',
            name='cidadeEstado',
        ),
        migrations.AddField(
            model_name='fornecedormodel',
            name='cidade',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='fornecedormodel',
            name='uf',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 0, 35, 4, 654601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 0, 35, 4, 654563, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 0, 35, 4, 608951, tzinfo=utc)),
        ),
    ]
