# Generated by Django 2.2.4 on 2020-01-10 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200110_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contapagarmodel',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 29, 29, 801893, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 29, 29, 801876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 14, 29, 29, 781746, tzinfo=utc)),
        ),
    ]
