# Generated by Django 2.2.4 on 2020-01-10 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200110_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contarecebermodel',
            old_name='descricao',
            new_name='observacao',
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 40, 32, 334143, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 40, 32, 334125, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 19, 40, 32, 314039, tzinfo=utc)),
        ),
    ]
