# Generated by Django 2.2.4 on 2019-12-17 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191217_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 1, 59, 17, 58433, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 1, 59, 17, 58393, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 1, 59, 17, 12502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='fornecedormodel',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedormodel',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
