# Generated by Django 2.2.4 on 2019-12-19 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191217_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='colaboradorModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('função', models.CharField(blank=True, max_length=300, null=True)),
                ('dataAdmissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataDesligamento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'Disponível'), ('2', 'Alocado'), ('3', 'Afastado'), ('4', 'Desligado')], default=1, max_length=1)),
                ('encarregado', models.CharField(blank=True, max_length=300, null=True)),
                ('setor', models.CharField(blank=True, max_length=300, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('uf', models.CharField(blank=True, max_length=300, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 50, 20, 716518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 50, 20, 716480, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 50, 20, 663180, tzinfo=utc)),
        ),
    ]
