# Generated by Django 2.2.4 on 2019-12-19 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191219_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradormodel',
            old_name='função',
            new_name='funcao',
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 51, 7, 120443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 51, 7, 120401, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 2, 51, 7, 67063, tzinfo=utc)),
        ),
    ]
