# Generated by Django 2.2.4 on 2019-12-22 18:29

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191221_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='clienteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('contato', models.CharField(blank=True, max_length=300, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('1', 'Disponível'), ('2', 'Bloqueado')], default=1, max_length=1)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=300, null=True)),
                ('uf', models.CharField(blank=True, max_length=300, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='colaboradormodel',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 18, 29, 17, 536666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cadastrosite',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 18, 29, 17, 536666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 18, 29, 17, 458783, tzinfo=utc)),
        ),
    ]
